name = "mayura-bot"
main = "src/index.js"
compatibility_date = "2026-03-24"

[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "16f852aca70c4596a93845091d054e10"

[[r2_buckets]]
binding = "PDF_CACHE"
bucket_name = "mayura-pdf-cache"

[vars]
SECRET_PATH = "asadsdflkgnlsdfgifdjdmhlsdglsfghmsfll"